// This file is automatically generated but enhanced with an API Proxy wrapper.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const originalSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper untuk memanggil API Gateway Proxy di serverless function
async function callRpcProxy(fnName: string, params: any) {
  try {
    const token = localStorage.getItem("lab_jwt_token");
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
    }

    const res = await fetch(`/api/rpc?fn=${fnName}`, {
      method: 'POST',
      credentials: 'include', // kirim httpOnly cookie otomatis
      headers,
      body: JSON.stringify(params || {}),
    });

    const contentType = res.headers.get("content-type");
    let resultData = null;
    if (contentType && contentType.includes("application/json")) {
      resultData = await res.json();
    } else {
      resultData = await res.text();
    }

    if (!res.ok) {
      return { 
        data: null, 
        error: { 
          message: (resultData && typeof resultData === 'object' && 'error' in resultData) 
            ? (resultData as any).error 
            : (resultData || 'API Proxy error'), 
          status: res.status 
        } 
      };
    }

    // Jika kembalian berupa objek error buatan database
    if (resultData && typeof resultData === 'object' && 'error' in resultData) {
      return { data: null, error: { message: (resultData as any).error } };
    }

    return { data: resultData, error: null };
  } catch (err: any) {
    return { data: null, error: { message: err.message || 'Network error' } };
  }
}

// Gunakan Proxy ES6 untuk mencegat pemanggilan supabase.rpc secara transparan
export const supabase = new Proxy(originalSupabase, {
  get(target, prop, receiver) {
    if (prop === 'rpc') {
      return (fnName: string, params: any) => {
        const promise = callRpcProxy(fnName, params);
        
        const makeThenable = (p: Promise<any>): any => ({
          then: (onf: any, onr: any) => p.then(onf, onr),
          catch: (onr: any) => p.catch(onr),
          finally: (onf: any) => p.finally(onf),
          single: () => makeThenable(p.then(res => ({ ...res, data: Array.isArray(res.data) ? res.data[0] : res.data }))),
          maybeSingle: () => makeThenable(p.then(res => ({ ...res, data: (Array.isArray(res.data) && res.data.length > 0) ? res.data[0] : (res.data || null) })))
        });

        return makeThenable(promise);
      };
    }
    return Reflect.get(target, prop, receiver);
  }
}) as unknown as typeof originalSupabase;