// This file is automatically generated but enhanced with an API Proxy wrapper.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const originalSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Daftar fungsi publik yang tidak perlu melewati proxy serverless (tetap panggil Supabase langsung)
const PUBLIC_RPCS = [
  'check_username_exists',
  'login_user',
  'register_user',
  'get_public_settings',
  'get_qr_session_secure',
  'get_renter_items_secure'
];

// Helper untuk memanggil API Gateway Proxy di serverless function
async function callRpcProxy(fnName: string, params: any) {
  try {
    const token = localStorage.getItem("lab_jwt_token");
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
    }

    const res = await fetch(`/api/rpc?fn=${fnName}`, {
      method: 'POST',
      headers,
      body: JSON.stringify(params || {}),
    });

    const contentType = res.headers.get("content-type");
    let resultData = null;
    if (contentType && contentType.includes("application/json")) {
      resultData = await res.json();
    } else {
      resultData = await res.text();
    }

    if (!res.ok) {
      return { 
        data: null, 
        error: { 
          message: (resultData && typeof resultData === 'object' && 'error' in resultData) 
            ? (resultData as any).error 
            : (resultData || 'API Proxy error'), 
          status: res.status 
        } 
      };
    }

    // Jika kembalian berupa objek error buatan database
    if (resultData && typeof resultData === 'object' && 'error' in resultData) {
      return { data: null, error: { message: (resultData as any).error } };
    }

    return { data: resultData, error: null };
  } catch (err: any) {
    return { data: null, error: { message: err.message || 'Network error' } };
  }
}

// Gunakan Proxy ES6 untuk mencegat pemanggilan supabase.rpc secara transparan
export const supabase = new Proxy(originalSupabase, {
  get(target, prop, receiver) {
    if (prop === 'rpc') {
      return (fnName: string, params: any) => {
        // Jika fungsi termasuk publik, panggil supabase asli langsung
        if (PUBLIC_RPCS.includes(fnName)) {
          return target.rpc(fnName as any, params);
        }
        
        // Untuk RPC sensitif lainnya, alihkan ke proxy serverless kita
        const promise = callRpcProxy(fnName, params);
        
        // Kita simulasikan chain methods Supabase seperti .single() dan .maybeSingle()
        const chainObject = {
          then: (onfulfilled: any, onrejected: any) => promise.then(onfulfilled, onrejected),
          catch: (onrejected: any) => promise.catch(onrejected),
          finally: (onfinally: any) => promise.finally(onfinally),
          single: () => {
            const singlePromise = promise.then(res => {
              if (res.error) return res;
              const data = res.data;
              return {
                data: Array.isArray(data) ? data[0] : data,
                error: null
              };
            });
            return {
              then: (onf: any, onr: any) => singlePromise.then(onf, onr),
              catch: (onr: any) => singlePromise.catch(onr),
              finally: (onf: any) => singlePromise.finally(onf)
            };
          },
          maybeSingle: () => {
            const maybeSinglePromise = promise.then(res => {
              if (res.error) return res;
              const data = res.data;
              return {
                data: (Array.isArray(data) && data.length > 0) ? data[0] : (data || null),
                error: null
              };
            });
            return {
              then: (onf: any, onr: any) => maybeSinglePromise.then(onf, onr),
              catch: (onr: any) => maybeSinglePromise.catch(onr),
              finally: (onf: any) => maybeSinglePromise.finally(onf)
            };
          }
        };

        return chainObject;
      };
    }
    return Reflect.get(target, prop, receiver);
  }
}) as unknown as typeof originalSupabase;